name: gallery-app
version: 2.9.1
summary: Gallery app
description: Gallery application for your photo collection
confinement: strict

apps:
  gallery-app:
    command: desktop-launch gallery-app
    plugs:
      - x11
      - home

parts:
  gallery:
    source: ./
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-packages:
      - build-essential
      - cmake
      - gettext
      - intltool
      - suru-icon-theme
      - pkg-config
      - libexiv2-dev
      - libgl1-mesa-dev
      - libgles2-mesa-dev
      - libmediainfo-dev
      - libqt5opengl5-dev
      - libqt5svg5
      - qt5-default
      - qtbase5-dev
      - qtdeclarative5-dev
      - python3-all
      - libexpat1-dev
      - zlib1g-dev
    stage-packages:
      - ubuntu-sdk-libs
      - qtubuntu-desktop
      - libqt5gui5
      - qtdeclarative5-ubuntu-thumbnailer0.1
    after: [desktop/qt5]
