name: gallery-app
version: 2.9.1
summary: Gallery app
description: Gallery application for your photo collection
confinement: strict

apps:
  gallery-app:
    command: desktop-launch gallery-app
    plugs: [unity7, opengl, home]

parts:
  gallery:
    source: ./
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-packages:
      - cmake
      - gettext
      - intltool
      - python3
      - pkg-config
      - libexiv2-dev
      - libmediainfo-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - libexpat1-dev
      - zlib1g-dev
    stage-packages:
      - ubuntu-sdk-libs
      - qtubuntu-desktop
      - qtdeclarative5-ubuntu-thumbnailer0.1
    after: [desktop/qt5]
