name: gallery-app
version: 2.9.1
summary: Gallery app
description: Gallery application for your photo collection
confinement: devmode
grade: devel

apps:
  gallery-app:
    command: bin/wrapper
    plugs: [unity7, opengl, home, thumbnailer, platform]

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  gallery:
    source: ./
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-packages:
      - cmake
      - gettext
      - intltool
      - python3
      - pkg-config
      - libexiv2-dev
      - libmediainfo-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - libexpat1-dev
      - zlib1g-dev
    stage-packages:
      - xdg-user-dirs
      - qtdeclarative5-ubuntu-ui-extras0.2
    snap:
      # gallery-app
      - usr/bin/gallery-app
      - usr/share/applications
      - usr/share/content-hub
      - usr/share/gallery-app
      - usr/share/icons
      - usr/share/locale/*/LC_MESSAGES/gallery-app.mo
      - usr/share/url-dispatcher/urls/*
      # xdg-user-dirs
      - usr/share/locale
      # ui-extras
      - usr/lib/x86_64-linux-gnu/qt5/qml/Ubuntu/Components/Extras
      - usr/share/doc/qtdeclarative5-ubuntu-ui-extras0.2/copyright
    after:
      - desktop-ubuntu-app-platform

  gallery-copy:
    source: snap
    plugin: dump
    organize:
      wrapper: bin/wrapper
      test.jpg: test/test.jpg

