name: gallery-app
version: 0.0.67+17.04.20161213-0ubuntu1
summary: Gallery app
description: Gallery application for your photo collection
confinement: devmode
grade: stable

apps:
  gallery-app:
    command: desktop-launch $SNAP/bin/wrapper
    plugs: [unity7, unity8, opengl, home, platform, mir] # "thumbnailer" still missing

plugs:
  platform:
    interface: content
    content: ubuntu-app-platform1
    target: ubuntu-app-platform
    default-provider: ubuntu-app-platform

parts:
  gallery:
    source: ./
    plugin: cmake
    configflags: [-DCMAKE_INSTALL_PREFIX=/usr, -DCLICK_MODE=off]
    build-attributes: [no-system-libraries]
    build-packages:
      - cmake
      - gettext
      - intltool
      - python3
      - pkg-config
      - libexiv2-dev
      - libmediainfo-dev
      - qtbase5-dev
      - qtdeclarative5-dev
      - libexpat1-dev
      - zlib1g-dev
    stage-packages:
      - xdg-user-dirs
      - libmediainfo0v5
      - libzen0v5
      - libmms0
      - libtinyxml2-2v5
    snap:
      # gallery-app
      - usr/bin/gallery-app
      - usr/share/applications
      - usr/share/content-hub
      - usr/share/gallery-app
      - usr/share/icons
      - usr/share/locale/*/LC_MESSAGES/gallery-app.mo
      - usr/share/url-dispatcher/urls/*
      - usr/lib/*/libexiv2.so.14*
      # xdg-user-dirs
      - usr/bin/xdg-user-dir
      - usr/bin/xdg-user-dirs-update
      - etc/xdg
      - etc/X11/Xsession.d/60xdg-user-dirs-update
      - usr/share/locale
      # libmediainfo0v5
      - usr/lib/*/libmediainfo.so.*
      # libzen0v5
      - usr/lib/*/libzen.so.* 
      # libmms0
      - usr/lib/*/libmms.so.*
      # libtinyxml2-2v5
      - usr/lib/*/libtinyxml2.so.*

    after:
      - desktop-ubuntu-app-platform

  gallery-copy:
    source: snap
    plugin: dump
    organize:
      wrapper: bin/wrapper
